spring.application.name=simoviteai-chatbot
server.port=8084

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management.endpoints.web.exposure.include=*

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.ai.openai.api-key=${GROQ_SERVER}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct
#spring.ai.ollama.base-url=${OLLAMA_SERVER:http://localhost:11434}

#spring.ai.ollama.chat.model=llama3.2
# Force la précision pour éviter les hallucinations de format
spring.ai.openai.chat.options.temperature=0.1

spring.ai.mcp.client.streamable-http.connections.catalog.url= ${CATALOG_Service_URL:http://localhost:8081/mcp}

discord.token=${DISCORD_BOT_TOKEN}
# Enable the bot to actually see what people type
discord.gateway-intents=MESSAGE_CONTENT, DIRECT_MESSAGES,GUILD_MESSAGES
spring.ai.openai.chat.options.max-tokens=300
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.ai=DEBUG
