spring.application.name=SimoViteAI_ChatBot

server.port=8084


spring.ai.ollama.base-url=${OLLAMA_SERVER:http://localhost:11434}

spring.ai.ollama.chat.model=llama3.2

spring.ai.ollama.chat.options.temperature=0.2

spring.cloud.discovery.enabled=true

spring.ai.mcp.client.streamable-http.connections.catalog.url= ${CATALOG_Service_URL:http://localhost:8081/mcp}

discord.token=${DISCORD_BOT_TOKEN}
