spring.application.name=SimoViteAI_ChatBot

server.port=8084

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management.endpoints.web.exposure.include=*

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.ai.ollama.base-url=${OLLAMA_SERVER:http://localhost:11434}

spring.ai.ollama.chat.model=llama3.2


spring.cloud.discovery.enabled=true

spring.ai.mcp.client.streamable-http.connections.catalog.url= ${CATALOG_Service_URL:http://localhost:8081/mcp}

discord.token=${DISCORD_BOT_TOKEN}
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.chat.options.num-ctx=4096
spring.ai.mcp.client.streamable-http.initialize-on-startup=false
