apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['simovite-order:8082']
            labels:
              application: 'order-service'
      - job_name: 'delivery-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['simovite-delivery:8083']
            labels:
              application: 'simovite-delivery'
      - job_name: 'catalog-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['simovite-catalog:8081']
            labels:
              application: 'simovite-catalog'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-service
  template:
    metadata:
      labels:
        app: prometheus-service
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 9090
  type: LoadBalancer
