spring.application.name=Gateway_service
server.port=8888
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

#spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
#
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://front-app-service:4200,http://localhost:4200
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
